name: cryptoAppll
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3


  cloud_firestore: ^3.1.6
  firebase_core: ^1.11.0
  firebase_auth: ^3.3.5
  http: ^0.13.4
  provider: ^6.0.2
  fl_chart: ^0.41.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/BNB.png
    - assets/icons/Ethereum.png
    - assets/icons/Terra.png
    - assets/icons/Solana.png
    - assets/icons/USDCoin.png
    - assets/icons/Polkadot.png
    - assets/icons/Tether.png
    - assets/icons/Cardano.png
    - assets/icons/XRP.png
    - assets/icons/DogeCoin.png
    - assets/icons/Bitcoin.png
    - assets/icons/Avalanche.png



